default_context:
  project_name: 'kiezbox-backend'
  project_slug: 'kiezbox-backend'
  domain_main: 'kiezbox-backend.com'
  domain_staging: 'stag.kiezbox-backend.com'
  docker_swarm_stack_name_main: 'kiezbox-backend-com'
  docker_swarm_stack_name_staging: 'stag-kiezbox-backend-com'
  secret_key: 'd54f98ce07699a7183ed5c9ead617af5bccbf52dc1748f2d0eccf19db5fd61b9'
  first_superuser: 'admin@kiezbox-backend.com'
  first_superuser_password: '12345'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.kiezbox-backend.com", "https://stag.kiezbox-backend.com", "https://kiezbox-backend.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@kiezbox-backend.com'
  postgres_password: '12345'
  pgadmin_default_user: 'admin@kiezbox-backend.com'
  pgadmin_default_user_password: '12345'
  traefik_constraint_tag: 'kiezbox-backend.com'
  traefik_constraint_tag_staging: 'stag.kiezbox-backend.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:12345'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
